# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TAGGER_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${TAGGER_MONGO_PASS}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${TAGGER_MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${TAGGER_MONGO_PASS}

  tagger:
    image: tagger
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./documents:/server/documents
    environment:
      TAGGER_MONGO_USER: ${TAGGER_MONGO_USER}
      TAGGER_MONGO_PASS: ${TAGGER_MONGO_PASS}
      TAGGER_MONGO_HOST: "mongo"
      TAGGER_MONGO_PORT: "27017"
